FROM golang:1.23.1
ARG PORT

# COPY source destination
COPY ./learn-go-cicd /bin/learn-go-cicd

# Specify Port the server will use
ENV PORT=$PORT

ENTRYPOINT ["/bin/learn-go-cicd"]

# docker build . -t goserver:latest
# docker run -p 8080:8080 goserver
